config/routes.rb
Yoyoburger::Application.routes.draw do

  resources :contact_forms
  resources :users
  resources :sessions,only:[:new,:create,:destroy]
  resources :messages,only:[:index, :create]
  resources :addresses,only:[:new,:create,:edit,:update,:destroy]
  resources :menu_items

  root 'static_pages#home'
  
  post 'contactform' => 'contactform#create'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/contact', to:'static_pages#contact', via:'get'
  match '/about', to:'static_pages#about',via:'get'

  match '/menu/:categoryID', to: 'static_pages#menu', via: 'get'

  match '/menu',to:'static_pages#menu',via:'get'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="col-md-4">
      <div class="footerInside">
        <h3>About</h3>

        Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus.

        <h3 class="footerLogo">YoYo Burger</h3>

        <p><span class="glyphicon glyphicon-phone-alt"></span> : 0117 930 4353</p>
        <p><span class="glyphicon glyphicon-map-marker"></span> : 6 Byron Pl, Avon BS8 1JT</p>
        <p>e: hello@yoyoburger.co.uk</p>
      </div>
    </div>

    <div class="col-md-4">
      <div class="footerInside">
        <h3>Connect</h3>

        <div class="social-icons">
          <ul>
            <li class="facebookFooter" style="background-color: #BBBBBB">
              <a href="http://www.twitter.com/" target="_blank">Facebook</a>
            </li>

            <li class="twitterFooter" style="background-color: #BBBBBB">
              <a href="http://www.twitter.com/" target="_blank">Twitter</a>
            </li>

            <li class="googleplusFooter" style="background-color: #BBBBBB">
              <a href="http://www.twitter.com/techandallcom" target="_blank">Google+</a>
            </li>
          </ul>
        </div>

        <div class="gmaps">

          <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA3a3922x9T1CZwTmREE6Nc51k2lGZGtrE&sensor=false"></script>
          <script type="text/javascript" src="http://www.map-generator.org/map/iframejs/422ec153-b462-4aea-93dd-05cf1ab57b88?key=AIzaSyA3a3922x9T1CZwTmREE6Nc51k2lGZGtrE&width=300px&height=150px"></script>
          <div id ="mapid-422ec153-b462-4aea-93dd-05cf1ab57b88"></div>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="footerInside">
        <h3>Newsletter</h3>

        <form class="navbar-form" role="search">
            <div class="form-group search-inner">
              <input type="text" class="form-control" placeholder="Email">
              <a href="" class="glyphicon glyphicon-chevron-right"></a>
            </div>

          </form>
      </div>
    </div>
  </div>
</div>

<div class="bottomFooter">
  <p>Copyright © Built by Team Nocturnal. All rights reserved.</p>
  <p><a href=""> Read the boring legal stuff </a></p>
</div>

app/views/layouts/_header.html.erb
<header class="header">
	<div class="container headerStyle">
		<div class="row">
			<div class="col-md-4 col-sm-4 col-xs-8">
				<%= link_to image_tag("yoyologo.png",class:"brand", alt: "Rails"), '' %>  
			</div>

			<div class="col-md-8 col-sm-8 col-xs-5 headernav">
				<div class="topnav">
					<nav class="navbar-default pull-right">
						<div class="navbar-header">
							<ul class="nav navbar-nav">

								<% if signed_in? %>

								<span class="navbar-text">Hi <%= current_user.first_name %>!</span>

								<li> <%= link_to '<span class="glyphicon glyphicon-cog">
								</span> My Account'.html_safe,    current_user %></li>

								<li><%= link_to '<span class="glyphicon glyphicon-tower">
								</span> Loyalty Points: 290 '.html_safe, current_user %></li>


								<li><%= link_to '<span class="glyphicon glyphicon-user">
								</span> Sign Out'.html_safe, signout_path, method:"delete" %></li>

								<%else%>

								<li><%= link_to '<span class="glyphicon glyphicon-cog">
								</span> My Account'.html_safe,    signin_path %></li>


								<li><%= link_to '<span class="glyphicon glyphicon-user">
								</span> Register'.html_safe,   signup_path %></li>

								<%end%>

								<li><%= link_to '<span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart <span class="badge">2</span> Total: £12.32'.html_safe, '#'%></li>

							</ul>
						</div>
					</nav>
				</div>

				<div class="bottomnav">
					<nav class="navbar-default">
						<div class="navbar-header">
							<ul class="nav navbar-nav">
								<li><%= link_to '<span class="glyphicon glyphicon-home">
									</span> HOME'.html_safe,root_path,{:class=>"activeLink"} %>
								</li>
								<li class="dropdown">
									<%= link_to 'MENU <span class ="caret"></span>'.html_safe, "#{menu_path}?categoryID=2", {:class=>"dropdown-toggle"} %>
								</li>
								<li><%= link_to "ABOUT",    about_path %></li>
								<li><%= link_to "CONTACT",    contact_path %></li>
						</ul>
					</div>


					<form class="navbar-form pull-right" role="search">
						<div class="form-group search-inner">
							<input type="text" class="form-control" placeholder="Search">
							<a href="" class="glyphicon glyphicon-chevron-right"></a>
						</div>

					</form>
				</nav>
			</div>




		</div>
	</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>YoYo Burger | <%= yield(:title) %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim'%>
</head>
<body>

	<div class="container">

		<%= render 'layouts/header'%>

		<br/>

		<div class="main">
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</div>


		<%= render 'layouts/footer' %>

	</div>
	<%= debug(params) if Rails.env.development? %>


</body>
</html>